image: node:16.13.0

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - prod


prod:
  type: deploy
  stage: prod
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME_PROD --api-key=$HEROKU_API_KEY
  only:
    - prod